stages:
  - androidbuild
  - androidtest

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - monreal                  # <-- change to your runner's tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Game_GUI_V1/gradlew
  script:
    - cd Game_GUI_V1                   # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build
  only:
    refs:
      - monreal_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - monreal                  # <-- change to your runner's tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Game_GUI_V1/gradlew
  script:
    - cd Game_GUI_V1                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - monreal_CICD
    changes:
      - Frontend/**/*
