stages:
  - androidbuild
  - androidtest

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
    - Nick_Doty                  # <-- change to your runner's tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Game_GUI_V1/gradlew
  script:
    - cd Game_GUI_V1                   # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build
  only:
    refs:
      - Nick_Doty_CICD
    changes:
      - Game_GUI_V1/**/*

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  tags:
    - Nick_Doty                  # <-- change to your runner's tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Game_GUI_V1/gradlew
  script:
    - cd Game_GUI_V1                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - Nick_Doty_CICD
    changes:
      - Game_GUI_V1/**/*
